# Required
baseURL = "https://example.com"
languageCode = "en-us"
title = "carrd50"
theme = "carrd50"

# Optional
googleAnalytics = ""

[params]
    # Required #
    author = "Ying Wang"
    email = "me@yingw787.com"
    description = "Port of Pro Template #50 by https://carrd.co"

    # Optional #
    font = "Space Mono" # Available fonts include: ["Space Mono"]. Double check file "css.html" for full Google Fonts API request.
    titleImage = "img/image01.png"
    titleTextColor = "#FFFFFF"

    # backgroundColor = "#002b36" # Solarized Dark Base03
