# Required
baseURL = "https://example.com"
languageCode = "en-us"
title = "carrd50"
theme = "carrd50"

# Optional
googleAnalytics = "$YOUR_GOOGLE_ANALYTICS"

[menu]
# Navbar items
[[menu.nav]]
name = "Name1"
url = "Href1"
weight = 1

[params]
    # Required #
    author = "Ying Wang"
    email = "me@yingw787.com"
    description = "Port of Pro Template #50 by https://carrd.co"
    copyrightYear = "2019"
    favicon = "img/favicon.png"

    # Navbar #
    firstElementText = "Text1"
    firstElementHref = "#Href1"
    thirdElementText = "Text3"
    thirdElementHref = "#Href3"

    # Optional #
    font = "Space Mono" # Available fonts include: ["Space Mono"].
    bodyTextColor = "#FFFFFF"
    backgroundColor = "#1C76B8"

    formInputColor = "#666666"
    formBackgroundColor = "#FFFFFF"
    formSelectedColor = "#1ABC9C"

    buttonColor = "#FFFFFF"
    buttonBackgroundColor = "#3BACFF"

    footerTextColor = "#FFFFFF"

    mailchimpURL = "$YOUR_MAILCHIMP_URL"
    mailchimpBotDecoyLink = "$YOUR_MAILCHIMP_BOT_DECOY_LINK"
